### PR TITLE
Fix for #93 - Add breadcrumbs to docs and all other pages

### PR DESCRIPTION
**Pull request by froschdesign**
See #93

### CODE REVIEW

**Comment by samsonasik** [comment]
@froschdesign it need rebase

**Comment by froschdesign** [comment]
@samsonasik 
I will work on it.

**Comment by vrkansagara** [comment]
@froschdesign  this issue would be closed!

**Comment by froschdesign** [comment]
@vrkansagara 
Why?

**Comment by vrkansagara** [comment]
@froschdesign I thinks this is resolved yet and a long time so.

**Pull request closed without merging**
