### PR TITLE
Add link to the talk on Youtube

### PR DESCRIPTION
**Pull request by danizord**
Zend uploaded the talk in Youtube today.

### CODE REVIEW

**Comment by froschdesign** [comment]
@danizord 
Why replace? Please include both links.

**Comment by danizord** [comment]
@froschdesign done :+1:

**Comment by danizord** [comment]
@froschdesign done :+1:

**Comment by danizord** [comment]
@froschdesign is mergeable? :D

**Comment by froschdesign** [comment]
Must be fixed on new version of the website.

**Pull request closed without merging**
