### PR TITLE
Fixes zf2-documentation/#1516

### PR DESCRIPTION
**Pull request by samsonasik**
https://github.com/zendframework/zf2-documentation/issues/1516 /cc @Ocramius

### CODE REVIEW

**Comment by froschdesign** [comment]
Should we also add a notice for version 2.4 and LTS?!

**Comment by samsonasik** [comment]
any wording suggestion?

**Comment by froschdesign** [comment]
A new entry for long term support and the PHP version would be nice.
On the LTS page we should also add a notice for the PHP version.

What do you think?

**Comment by samsonasik** [comment]
I've updated in faq page for LTS version, for in lts page, could you point me where part need to be updated?

**Comment by samsonasik** [comment]
@froschdesign merge-able ?

**Comment by froschdesign** [comment]
Yes, later today…

**Comment by samsonasik** [comment]
@froschdesign ping for merge ;)

**Comment by samsonasik** [comment]
ping @froschdesign @weierophinney for merge

**Comment by samsonasik** [comment]
@froschdesign what hold it to get merge?

**Pull request closed without merging**
