### PR TITLE
SASS mixins for flexbox

### PR DESCRIPTION
**Pull request by weierophinney**
This is meant to address #157. Instead of using Foundation grids, it continues to use flexbox, but uses SASS mixins for flexbox that ensure that it should work cross-platform.

### CODE REVIEW

**Comment by weierophinney** [comment]
@spectravp and @froschdesign -- can you test in Safari and let me know if this works for you?

**Comment by froschdesign** [comment]
Use bourbon: [Flexbox](http://bourbon.io/docs/#flexbox)

**Comment by spectravp** [comment]
@weierophinney Tested in Safari 8.0.2 and all was well.

**Comment by weierophinney** [comment]
Deployed. :)

**Comment by froschdesign** [comment]
:+1:

**Pull request merged**
